### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [capitalkind/GameGame#2]
Malcolm,

Really like the design on this and how you incorporated everything into the theme. The game looks great and functions nicely. One minor bug I did notice was sometimes when you're clicking some of your matches disappear from the screen, though your score is the same. Maybe take a look at your code and see why this is happening. Overall you did a great job and the timer definitely adds a sense of urgency.

**Comment by ajhofferber** [comment]
Hey Malcolm,

You project looks great! I really like the idea of comparing the amount of pairs made with the amount of guesses. Also, I like the timing element, it makes it more exciting!  I noticed that one time it matched two logos that weren't actually matching... So I dont know what's going on there! but otherwise it is great. I would maybe consider making the fade animations a bit quicker.  It makes it so you can click and have more that two appearing at a time. Not sure if that is what is possibly causing the bug?

Overall, I think you did a really great job!

Score: 2 (see project markdown for score metric)

-Ash
